#!/bin/bash
set -e

echo "=========================================="
echo "--- Starting On-Start Script (V5 - Final & Robust) ---"
echo "=========================================="

echo "[OK] Environment is pre-configured by Docker image."

# --- Biến Môi trường ---
if [ -z "$NGROK_AUTHTOKEN" ]; then
    echo "[ERROR] NGROK_AUTHTOKEN is not set!"
    exit 1
fi
if [ -z "$UPSTASH_REDIS_URL" ]; then
    echo "[ERROR] UPSTASH_REDIS_URL is not set!"
    exit 1
fi

# --- Cấu hình Model và Chế độ VRAM ---
export MODEL_SET="${MODEL_SET:-mini_turbo}"
export LOW_VRAM_MODE="${LOW_VRAM_MODE:-false}"

# --- THIẾT LẬP ĐƯỜNG DẪN & MÔI TRƯỜNG ---
export PROJECT_ROOT="/app/REST_API_GPU_V2R"
export HUNYUAN_ROOT="${PROJECT_ROOT}/Hunyuan3D-2"
export PRELOAD_SCRIPT_PATH="${PROJECT_ROOT}/api/download_models_runtime.py"

# Thêm PROJECT_ROOT vào PYTHONPATH để Python tìm thấy module `api`
export PYTHONPATH="${PROJECT_ROOT}:${PYTHONPATH}"
echo "[SETUP] PYTHONPATH set to: ${PYTHONPATH}"
echo "------------------------------------------"


# --- BƯỚC 1: TẠO SCRIPT TẢI MODEL TẠM THỜI ---
echo "--- Step 1: Generating a temporary model pre-loader script... ---"
# Sử dụng 'Here Document' (cat <<EOF) để tạo file Python một cách an toàn
cat << EOF > "${PRELOAD_SCRIPT_PATH}"
# This is a temporary script generated by on-start.sh
import sys
import os
import argparse

# Cần thêm dòng này để đảm bảo import hoạt động ổn định
sys.path.insert(0, "${PROJECT_ROOT}")

from api.models import ModelManager

def main():
    parser = argparse.ArgumentParser(description="Hunyuan3D Model Pre-downloader")
    parser.add_argument("--model_set", type=str, required=True)
    parser.add_argument('--low_vram_mode', action='store_true')
    parser.add_argument('--device', type=str, default='cuda')
    parser.add_argument('--cache-path', type=str, default='api_cache')
    parser.add_argument('--enable_flashvdm', action='store_true')
    parser.add_argument('--mc_algo', type=str, default='mc')
    parser.add_argument('--compile', action='store_true')
    args = parser.parse_args()

    print(f"[Pre-loader] Initializing ModelManager for model set: '{args.model_set}'...")
    try:
        ModelManager(args)
        print("[Pre-loader] All models downloaded successfully!")
    except Exception as e:
        print(f"[Pre-loader] FATAL ERROR during model download: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
EOF

echo "[OK] Pre-loader script created at: ${PRELOAD_SCRIPT_PATH}"
echo "------------------------------------------"


# --- BƯỚC 2: TẢI TRƯỚC MODEL ---
echo "--- Step 2: Executing the pre-loader script... ---"
echo "--- This may take a long time, please be patient. ---"

# **FIX LỖI "failed to load template"**
# Thay đổi thư mục làm việc (CWD) sang thư mục gốc của thư viện Hunyuan3D-2
# Điều này cực kỳ quan trọng để nó có thể tìm thấy các file assets của nó (ví dụ: ./assets/...)
cd "${HUNYUAN_ROOT}"
echo "[SETUP] Current Working Directory changed to: $(pwd)"

# Chuẩn bị cờ --low_vram_mode
LOW_VRAM_MODE_FLAG=""
if [[ "${LOW_VRAM_MODE}" == "true" ]]; then
    LOW_VRAM_MODE_FLAG="--low_vram_mode"
fi

# Chạy script vừa tạo. Script bash sẽ chờ cho đến khi nó hoàn thành.
python "${PRELOAD_SCRIPT_PATH}" --model_set "${MODEL_SET}" ${LOW_VRAM_MODE_FLAG}

echo "[OK] All models are now cached locally."
echo "------------------------------------------"


# --- BƯỚC 3: KHỞI ĐỘNG SERVER API ---
LOG_FILE="/tmp/server_log.txt"
echo "--- Step 3: Starting API server in background... Log file: $LOG_FILE ---"

# Chạy server chính. CWD vẫn đang là HUNYUAN_ROOT, và PYTHONPATH đã được set.
# Điều này đảm bảo server khởi động và hoạt động đúng.
python -m api.main --port 8080 --ngrok_authtoken "${NGROK_AUTHTOKEN}" \
                   --model_set "${MODEL_SET}" ${LOW_VRAM_MODE_FLAG} \
                   --cache-path "${PROJECT_ROOT}/api_cache" > $LOG_FILE 2>&1 &

SERVER_PID=$!
echo "--- Server started with PID: $SERVER_PID ---"
echo "------------------------------------------"


# --- CÁC BƯỚC CÒN LẠI (GIỮ NGUYÊN) ---
echo "--- Step 4: Waiting for Ngrok URL... (timeout: 120s) ---"
NGROK_URL=""
for i in {1..120}; do
    if ! ps -p $SERVER_PID > /dev/null; then
        echo "[ERROR] Server process (PID: $SERVER_PID) terminated unexpectedly!"
        echo "--- Displaying last 50 lines of log: ---"
        tail -n 50 $LOG_FILE
        exit 1
    fi
    if [ -f "$LOG_FILE" ]; then
        NGROK_URL=$(grep "PUBLIC URL" $LOG_FILE | sed 's/.*🌍 PUBLIC URL (NGROK TUNNEL): //')
        if [ ! -z "$NGROK_URL" ]; then break; fi
    fi
    echo "Waiting... (${i}s)"
    sleep 1
done

if [ -z "$NGROK_URL" ]; then
    echo "[ERROR] Failed to retrieve Ngrok URL within 120 seconds."
    echo "--- Displaying last 50 lines of log: ---"
    tail -n 50 $LOG_FILE
    exit 1
fi

echo "[OK] Captured Ngrok URL: $NGROK_URL"
echo "------------------------------------------"

echo "--- Step 5: Registering URL in Redis... ---"
# Quay về thư mục gốc của project để chạy register_url cho chắc chắn
cd "${PROJECT_ROOT}"
python -m api.register_url $NGROK_URL
echo "[OK] URL registered in Redis."
echo "=========================================="
echo "--- On-Start Script finished. Server is running in background. ---"
echo "--- You can check the log with: tail -f $LOG_FILE ---"
echo "=========================================="

wait $SERVER_PID
